language: php

php:
  - 5.3.7
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --prefer-source --no-interaction --dev
  - php composer.phar dump-autoload

script: phpunit